[SUPABASE]
SUPABASE_URL = "https://azshlhlqwguirhjxicym.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6c2hsaGxxd2d1aXJoanhpY3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDcxMDMsImV4cCI6MjA3NDE4MzEwM30.Nst64AplsSakggayJl8mZ5yMhG5zhfEoWZ5nJfZZfFw"

[SMTP]
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "shaiktabassum125@gmail.com"
SMTP_PASS = "dhuuiqdjphinfpzp"
